# DGraph Service for Railway
FROM dgraph/standalone:latest
EXPOSE 8080 9080
# Note: Healthcheck disabled - DGraph standalone doesn't include curl
# Railway will detect the service is running via the exposed ports
CMD ["dgraph", "standalone"]
